version: '1.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nelsonrodriguez
      POSTGRES_PASSWORD: Nelson451198
      POSTGRES_DB: Pruebadocker

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
